name: prometheus
author: fetchai
version: 0.7.0
type: connection
description: Connection for exposing agent metrics to prometheus server
license: Apache-2.0
aea_version: '>=1.0.0, <2.0.0'
fingerprint:
  README.md: Qmcqi2KXnpA15XMZDF87aRvVC6QtgWtSTYzv1vx5rJASBy
  __init__.py: QmWVrDiiePsr6vTnvbPTcDrayR89ji3hf25rs9V9TiJUPv
  connection.py: QmVzXbw9x15NTKVpMxrYQ212qu3gEQoFJtGfuFVCiw6cz7
fingerprint_ignore_patterns: []
connections: []
protocols:
- fetchai/prometheus:1.0.0
class_name: PrometheusConnection
config:
  host: 127.0.0.1
  port: 9090
excluded_protocols: []
restricted_to_protocols:
- fetchai/prometheus:1.0.0
dependencies:
  aioprometheus:
    version: <21.0.0,>=20.0.0
is_abstract: false
