name: Release Flow

# Controls when the action will run.
on:
  release:
    types: [published]

jobs:
  publish-pip-packages:
    name: Create Framework & Plugin Releases
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Build wheels and source tarball
        run: |
          echo Processing open-aea

  publish-aea-packages:
    name: Push Open AEA Packages
    runs-on: ubuntu-latest
    needs:
      - publish-pip-packages
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install dependencies
        run: |
          echo "install"


  publish-docs-images:
    name: Publish Docs Images
    runs-on: ubuntu-latest
    needs:
      - publish-aea-packages
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Docker image published"


  publish-user-images:
    name: Publish User Images
    runs-on: ubuntu-latest
    needs:
      - publish-aea-packages
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Docker image published"

  publish-deploy-images:
    name: Publish Deploy Images
    runs-on: ubuntu-latest
    needs:
      - publish-aea-packages
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Docker image published"

  publish-develop-images:
    name: Publish Develop Images
    runs-on: ubuntu-latest
    needs:
      - publish-aea-packages
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Docker image published"
